context:
  version: "0.10.0"

package:
  name: cargo-vet
  version: ${{ version }}

source:
  url: https://github.com/mozilla/cargo-vet/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 9e7f4ce013c1523f70788e5a720ddb9c3d09cdc7fa5df78cfb6196d4af0b5712

build:
  number: 0
  script:
    env:
      CARGO_PROFILE_RELEASE_STRIP: symbols
      CARGO_PROFILE_RELEASE_LTO: fat
    content:
      - if: unix
        then:
          - cargo auditable install --no-track --locked --root ${PREFIX} --path .
          - cargo-bundle-licenses --format yaml --output ${SRC_DIR}/THIRDPARTY.yml
      - if: win
        then:
          - cargo auditable install --no-track --locked --root %PREFIX% --path .
          - if errorlevel 1 exit 1
          - cargo-bundle-licenses --format yaml --output %SRC_DIR%/THIRDPARTY.yml
          - if errorlevel 1 exit 1

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - cargo-auditable
    - cargo-bundle-licenses

tests:
  - script:
      - cargo-vet --help

about:
  homepage: https://github.com/mozilla/cargo-vet
  repository: https://github.com/mozilla/cargo-vet
  documentation: https://mozilla.github.io/cargo-vet/
  summary: The cargo vet subcommand is a tool to help projects ensure that third-party Rust dependencies have been audited by a trusted entity.
  license: Apache-2.0 OR MIT
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
    - THIRDPARTY.yml


extra:
  recipe-maintainers:
    - xhochy
